training_pipeline_config:
  pipeline_name: 'customer'
  training_artifact_dir: 'artifacts'

data_ingestion_config:
  download_data_url: 'https://raw.githubusercontent.com/amankharwal/Website-data/master/marketing_campaign.csv'
  raw_data_dir: 'raw_data'
  ingested_data_dir: 'ingested_data'
  ingested_train_dir: 'train'
  ingested_test_dir: 'test'

data_validation_config:
  schema_file_path: 'schema.yaml'
  report_file_path: 'report.json'
  report_page_file_path: 'report.html'
